version: "2"
services:

  startpage:
    image: nginx:alpine
    restart: always
    container_name: startpage
    ports:
      - 80:80
    volumes:
      - ./startpage/public:/usr/share/nginx/html:ro

  minidlna:
    image: cytomich/rpi-docker-minidlna
    volumes:
      - ${DISK}:/media
    environment:
      - MINIDLNA_MEDIA_DIR=/media
      - MINIDLNA_PORT=8200
      - MINIDLNA_FRIENDLY_NAME=media-box
    network_mode: "host"
    restart: always

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - USER=1234
      - PASS=1234
    volumes:
      - ./transmission:/config
      - ${DISK}/download/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

  amule:
    image : otrodeteruel/amulepi
    container_name: amule
    environment:
      - PUID:1000
      - PGID:1000
    volumes:
      - ${DISK}/download/amule:/home/myuser/amule
    ports:
      - 4711:4711
      - 4712:4712
      - 8004:8004
      - 8006:8006/udp
      - 8007:8007/udp

  filebrowser:
    image : filebrowser/filebrowser:pi
    container_name: filebrowser
    restart: always
    volumes:
      - ./filebrowser/filebrowser.db:/database.db
      - ./filebrowser/filebrowser.json:/.filebrowser.json
      - ${DISK}/:/srv
    ports:
      - 8088:80

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer/data:/data
    ports:
      - 9000:9000

  metube:
    image: alexta69/metube
    container_name: metube
    ports:
      - "8081:8081"
    volumes:
      - ${DISK}/download/youtube:/downloads